[package]
name = "iterlist"
description = "Linked list with a cursor based api"
license = "0BSD"
repository = "https://github.com/slbsh/iterlist"
version = "0.3.5"
edition = "2021"
keywords = ["linked-list", "cursor", "data-structures"]
readme = "README.md"
